dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
script:
  - mkdir lib
  - cd lib
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - git checkout tags/release-1.10.0
  - cd ../../
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./test/yace_test
