dist: bionic
sudo: required
language:
  "c++"
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl
before_install:
  - pip install --user cpp-coveralls
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
script:
  - git submodule update --init
  - mkdir lib
  - cd lib
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - git checkout tags/release-1.10.0
  - cd ../../
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - make
  - ./test/yace_test
  # code coverage tests run in debug mode
  - export COVERALLS_SERVICE_NAME=travis-ci
  - export COVERALLS_REPO_TOKEN=713aLFBKTIEXfmmHWUvv41CqnWOoB90MJ
  - cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
  - make
  - make coveralls